### ISSUE TITLE
[REQUEST] menu such as adonis or HD

### ISSUE THREAD

**Issue by AlkalineBleach** [MochaTheDev/atlas#5]
**Is your feature request related to a problem? Please describe.**
it's a bit of a problem when you try and figure out all the commands, but theres no :commands or :cmds command so all you have to do is guess or look at the code which can be really annoying

**Describe the solution you'd like**
add a menu like adonis or HD

**Describe alternatives you've considered**
making a menu myself to unannoy myself but im a dumbass so it failed

**Comment by MochaTheDev** [comment]
Hey there~

There is actually a command. What version are you running?

**Comment by Bloxxerse** [comment]
@MochaTheDev it should be the newest version since it has the **loader_f** folder

**Comment by MochaTheDev** [comment]
> @MochaTheDev it should be the newest version since it has the **loader_f** folder

Give me a minute to do a quick test, I'll get back to you in a moment.

**Comment by MochaTheDev** [comment]
Are you getting this popup when the system boots?
![image](https://github.com/MochaTheDev/atlas/assets/52216888/0996d174-849b-4f32-926d-dfab116b4fa8)

**Comment by AlkalineBleach** [comment]
negative. :cmds doesnt work too

**Comment by MochaTheDev** [comment]
> negative. :cmds doesnt work too

DM me your settings file (Right Click > Save to file) on Discord @mocha______

**Comment by AlkalineBleach** [comment]
> > negative. :cmds doesnt work too
> 
> DM me your settings file (Right Click > Save to file) on Discord @mocha______

alright

**Comment by AlkalineBleach** [comment]
solved ^^^^^
